### ISSUE TITLE
Changelog module

### ISSUE THREAD

**Issue by joelvarty** [agility/agilitycms-documentation-site#10]
- Sidebars should be fixed width when visible
- Description should ALWAYS be on a separate line from the title.
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/4520625/153429014-7569cbaf-61c1-4a8c-b074-7af37ba6beaa.png">

**Comment by Jerbits** [comment]
https://github.com/agility/agilitycms-documentation-site/compare/bugfix_changelog_module_10?expand=1
